(* Libéré du désir… *)

char = "a" | "ë" | "'" | "\u{1F99D}" | "\"" | "\"";

option = "queqchose"
  | "autchose"
  | (* empty *);
  
 nom = "Joël", [ [ "J." ], "Présent"];
 
 hein = { char | nom }; 

ascii-displayable = '\u{20}'...'\u{7F}';

ascii-affichable = '\u{20}'..='\u{7F}';
